name: infinite_feed
description: The infinite feed project.
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  path: 1.8.1
  path_provider: 2.0.11
  equatable: 2.0.3
  bloc: 8.0.3
  flutter_bloc: 8.0.1
  video_player: 2.4.5
  dio: 4.0.6
  uuid: 3.0.6
  visibility_detector: 0.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true